[package]
name = "auto-from"
version = "0.1.0"
authors = ["David Ross <daboross@daboross.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["derive", "printing", "full"] }
quote = "0.6"
synstructure = "0.10"
proc-macro2 = "0.4"
